Table "dsc_channels_point_events" {
  "id" INT(11) [pk, not null, increment]
  "channel_id" INT(11) [not null, default: "0"]
  "utc_start" DATETIME [default: NULL]
  "utc_end" DATETIME [default: NULL]
  "settle_signals" INT(11) [not null, default: "0"]
  "total_signals_created" INT(11) [not null, default: "0"]
  "total_signals_closed" INT(11) [not null, default: "0"]
  "total_pips" INT(11) [not null, default: "0"]
  "avg_pips" DOUBLE [not null, default: "0"]
  "point" DOUBLE [not null, default: "0"]
  "medals" TINYINT(4) [not null, default: "0"]
  "last_qualify_id" INT(11) [not null, default: "0"]
  "prev_point" DOUBLE [not null, default: "0"]
  "prev_medal" TINYINT(4) [not null, default: "0"]
  "prev_channel_medal" TINYINT(4) [not null, default: "0"]
  "last_avg_pips_monthly" DOUBLE [default: NULL]
  "next_avg_profit_monthly" DOUBLE [default: NULL]
  "send_mail" TINYINT(4) [not null, default: "0"]

Indexes {
  (channel_id, utc_start, utc_end) [unique, name: "channel_id_utc_start_utc_end"]
  channel_id [name: "channel_id"]
  utc_start [name: "dt_start"]
  utc_end [name: "dt_end"]
  point [name: "point"]
  medals [name: "medals"]
  prev_point [name: "prev_month_point"]
  prev_medal [name: "prev_month_medal"]
  settle_signals [name: "settle_signals"]
  total_pips [name: "total_pips"]
  avg_pips [name: "avg_pips"]
  prev_channel_medal [name: "prev_channel_medal"]
  total_signals_created [name: "total_signals_created"]
  total_signals_closed [name: "total_signals_closed"]
  last_qualify_id [name: "last_qualify_id"]
  last_avg_pips_monthly [name: "last_avg_pips_monthly"]
  next_avg_profit_monthly [name: "next_avg_profit_monthly"]
}
}
