Table "dsc_dw_channel_pair_daily" {
  "id" INT(11) [pk, not null, increment]
  "channelid" INT(11) [not null]
  "pair" VARCHAR(16) [not null, default: ""]
  "dateid" DATETIME [not null]
  "cmd" VARCHAR(8) [not null, default: ""]
  "expired" INT(11) [not null, default: "0"]
  "pips" INT(11) [not null, default: "0"]
  "pips_gross_profit" INT(11) [not null, default: "0"]
  "pips_gross_loss" INT(11) [not null, default: "0"]
  "netprofit" DOUBLE(22,0) [not null, default: "0"]
  "gross_profit" DOUBLE(22,0) [not null, default: "0"]
  "gross_loss" DOUBLE(22,0) [not null, default: "0"]
  "trades" INT(11) [not null, default: "0"]
  "win_trades" INT(11) [not null, default: "0"]
  "loss_trades" INT(11) [not null, default: "0"]
  "avg_duration" INT(11) [not null, default: "0"]
  "copier" INT(11) [not null, default: "0"]
  "copier_win_trades" INT(11) [not null, default: "0"]
  "copier_loss_trades" INT(11) [not null, default: "0"]
  "copier_avg_duration" INT(11) [not null, default: "0"]
  "copier_expired" INT(11) [not null, default: "0"]
  "copier_volume" DOUBLE(22,0) [not null, default: "0"]
  "copier_netprofit" DOUBLE(22,0) [not null, default: "0"]
  "copier_gross_profit" DOUBLE(22,0) [not null, default: "0"]
  "copier_gross_loss" DOUBLE(22,0) [not null, default: "0"]
  "copier_pips" INT(11) [not null, default: "0"]
  "copier_pips_gross_profit" INT(11) [not null, default: "0"]
  "copier_pips_gross_loss" INT(11) [not null, default: "0"]

Indexes {
  (channelid, dateid, pair, cmd) [unique, name: "channelid_dateid_pair_cmd"]
  channelid [name: "channelid"]
  dateid [name: "dateid"]
  pair [name: "pair"]
}
}
