Table "dsc_signals_copy" {
  "id" INT(11) [pk, not null, increment]
  "signal_id" INT(11) [not null, default: "0"]
  "user_id" INT(11) [not null, default: "0"]
  "broker" TINYINT(4) [default: NULL]
  "mt4id" INT(11) [default: NULL]
  "symbol" VARCHAR(30) [default: NULL]
  "op" TINYINT(4) [default: NULL]
  "open_time" DATETIME [default: NULL]
  "volume" INT(11) [default: NULL]
  "ticket_id" INT(11) [default: NULL]
  "price" DOUBLE [default: NULL]
  "sl" DOUBLE [default: NULL]
  "tp" DOUBLE [default: NULL]
  "commission" DOUBLE [default: NULL]
  "storage" DOUBLE [default: NULL]
  "profit" DOUBLE [default: NULL]
  "pips" INT(11) [default: NULL]
  "close_price" DOUBLE [default: NULL]
  "close_time" DATETIME [default: NULL]
  "expired" INT(11) [default: "86400"]
  "reason" TINYINT(4) [not null, default: "0"]
  "state" TINYINT(4) [not null, default: "0"]
  "CREATED_AT" TIMESTAMP [default: NULL]
  "LAST_MODIFY" TIMESTAMP [default: NULL]

Indexes {
  signal_id [name: "signal_id"]
  user_id [name: "user_id"]
  mt4id [name: "mt4id"]
  op [name: "op"]
  open_time [name: "open_time"]
  volume [name: "volume"]
  ticket_id [name: "ticket_id"]
  profit [name: "profit"]
  close_time [name: "close_time"]
  CREATED_AT [name: "CREATED_AT"]
  LAST_MODIFY [name: "LAST_MODIFY"]
}
}
