Table "dsc_channels" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(11) [not null]
  "title" VARCHAR(25) [not null]
  "image" VARCHAR(255) [default: NULL]
  "caption" TEXT [default: NULL]
  "price" DOUBLE [not null, default: "0"]
  "price_last_update" DATETIME [default: NULL]
  "status" TINYINT(4) [not null, default: "1", note: '0:disabled; 1:active']
  "medals" TINYINT(4) [not null, default: "0"]
  "point" DOUBLE [not null, default: "0"]
  "last_qualify_id" INT(11) [not null, default: "0"]
  "mt4server" TINYINT(4) [default: NULL]
  "account" INT(11) [default: NULL]
  "locked" TINYINT(4) [not null, default: "0"]
  "created_time" BIGINT(20) [not null]
  "creator" INT(11) [default: NULL]
  "block_signal" TINYINT(4) [default: "0"]
  "private" TINYINT(4) [default: "0"]
  "show" TINYINT(4) [default: "1"]
  "contact_email" VARCHAR(50) [default: NULL]
  "recommend" INT(11) [not null, default: "0"]
  "total_active_subs" INT(11) [not null, default: "0"]
  "total_profit_scale" DOUBLE [not null, default: "0"]
  "total_pips" DOUBLE [not null, default: "0"]
  "total_signal" INT(11) [not null, default: "0"]
  "total_signal_expired" INT(11) [not null, default: "0"]
  "total_signal_profit" INT(11) [not null, default: "0"]
  "total_signal_loss" INT(11) [not null, default: "0"]
  "total_signal_success_rate" DOUBLE [not null, default: "0"]
  "total_signal_last_count" DATETIME [default: NULL]
  "last_post" DATETIME [default: NULL]
  "total_running_signal" INT(11) [default: NULL]
  "cur_month_signal" INT(11) [not null, default: "0"]
  "cur_month_signal_profit" INT(11) [not null, default: "0"]
  "cur_month_signal_loss" INT(11) [not null, default: "0"]
  "cur_month_signal_expired" INT(11) [not null, default: "0"]
  "cur_month_signal_success_rate" DOUBLE [not null, default: "0"]
  "cur_month_signal_pips" DOUBLE [not null, default: "0"]
  "cur_month_signal_profit_scale" DOUBLE [not null, default: "0"]
  "cur_month_signal_last_count" DATETIME [default: NULL]
  "last_month_signal" INT(11) [not null, default: "0"]
  "last_month_signal_profit" INT(11) [not null, default: "0"]
  "last_month_signal_loss" INT(11) [not null, default: "0"]
  "last_month_signal_expired" INT(11) [not null, default: "0"]
  "last_month_signal_success_rate" DOUBLE [not null, default: "0"]
  "last_month_signal_pips" DOUBLE [not null, default: "0"]
  "last_month_signal_profit_scale" DOUBLE [not null, default: "0"]
  "last_month_signal_last_count" DATETIME [default: NULL]
  "diff_week" INT(11) [not null, default: "0"]
  "post_per_week" INT(11) [not null, default: "0"]
  "need_update" TINYINT(4) [not null, default: "1"]
  "last_point_count" DATETIME [default: NULL]
  "avg_pips_monthly" DOUBLE [default: NULL]

Indexes {
  title [unique, name: "title"]
  (account, mt4server) [unique, name: "mt4server"]
  user_id [name: "user_id"]
  created_time [name: "created_time"]
  price [name: "price"]
  status [name: "status"]
  recommend [name: "recommend"]
  show [name: "show"]
  total_active_subs [name: "total_active_subs"]
  total_profit_scale [name: "total_profit_scale"]
  total_pips [name: "total_pips"]
  total_signal [name: "total_signal"]
  total_signal_expired [name: "total_signal_expired"]
  total_signal_profit [name: "total_signal_profit"]
  total_signal_loss [name: "total_signal_loss"]
  total_signal_success_rate [name: "total_signal_success_rate"]
  need_update [name: "need_update"]
  diff_week [name: "diff_week"]
  post_per_week [name: "post_per_week"]
  medals [name: "medals"]
  point [name: "point"]
  last_point_count [name: "last_point_count"]
  last_qualify_id [name: "last_qualify_id"]
  cur_month_signal [name: "cur_month_signal"]
  cur_month_signal_profit [name: "cur_month_signal_profit"]
  cur_month_signal_loss [name: "cur_month_signal_loss"]
  cur_month_signal_expired [name: "cur_month_signal_expired"]
  cur_month_signal_success_rate [name: "cur_month_signal_success_rate"]
  cur_month_signal_pips [name: "cur_month_signal_pips"]
  cur_month_signal_profit_scale [name: "cur_month_signal_profit_scale"]
  cur_month_signal_last_count [name: "cur_month_signal_last_count"]
  last_month_signal [name: "last_month_signal"]
  last_month_signal_profit [name: "last_month_signal_profit"]
  last_month_signal_loss [name: "last_month_signal_loss"]
  last_month_signal_expired [name: "last_month_signal_expired"]
  last_month_signal_success_rate [name: "last_month_signal_success_rate"]
  last_month_signal_pips [name: "last_month_signal_pips"]
  last_month_signal_profit_scale [name: "last_month_signal_profit_scale"]
  last_month_signal_last_count [name: "last_month_signal_last_count"]
  total_signal_last_count [name: "total_signal_last_count"]
  last_post [name: "last_post"]
  total_running_signal [name: "total_running_signal"]
  avg_pips_monthly [name: "avg_pips_monthly"]
}
}
