Table "dsc_payment" {
  "bill_no" INT(11) [pk, not null, increment]
  "bill_reff" INT(11) [not null, note: 'Channel ID']
  "bill_code" SMALLINT(6) [not null, default: "0"]
  "bill_date" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "bill_expired" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "bill_desc" VARCHAR(128) [not null, default: ""]
  "bill_currency" CHAR(3) [not null, default: ""]
  "bill_total" DOUBLE(22,0) [not null, default: "0"]
  "payment_channel" INT(11) [not null]
  "pay_type" TINYINT(4) [not null, default: "0"]
  "cust_no" INT(11) [not null]
  "cust_name" VARCHAR(128) [not null, default: ""]
  "msisdn" VARCHAR(64) [not null, default: ""]
  "email" VARCHAR(128) [not null, default: ""]
  "terminal" CHAR(2) [not null, default: ""]
  "product" VARCHAR(50) [not null, default: ""]
  "amount" DOUBLE(22,0) [not null, default: "0"]
  "qty" INT(11) [not null, default: "0"]
  "payment_plan" TINYINT(4) [not null, default: "0"]
  "tenor" CHAR(2) [not null, default: ""]
  "trx_id" VARCHAR(16) [default: NULL]
  "payment_total" DOUBLE [not null, default: "0"]
  "payment_date" DATETIME [default: NULL]
  "payment_status" TINYINT(4) [not null, default: "0", note: '0 Belum diproses; 1 Dalam proses; 2 Payment Success; 4 Payment Reserval; 5 Tagihan tidak ditemukan; 7 Payment Refused; 8 Payment Cancelled; 9 Unknown']
  "payment_reff" VARCHAR(32) [default: NULL]
  "comm" DOUBLE [default: NULL]
  "admin_fee" DOUBLE [default: NULL]
  "subs_expired" DATETIME [default: NULL]
  "source" TINYINT(4) [default: "1", note: '0: Internal, 1: Faspay']

Indexes {
  cust_no [name: "cust_no"]
  payment_channel [name: "payment_channel"]
  bill_reff [name: "bill_reff"]
  payment_date [name: "payment_date"]
  bill_code [name: "bill_code"]
}
  Note: 'https://faspay.co.id/docs/'
}
