Table "dsc_signals" {
  "id" INT(11) [pk, not null, increment]
  "channel_id" INT(11) [not null, default: "0"]
  "volume" INT(11) [not null, default: "0"]
  "symbol" VARCHAR(30) [default: NULL]
  "op" TINYINT(4) [default: NULL]
  "open_time" DATETIME [default: NULL]
  "price" DOUBLE [not null, default: "0"]
  "sl" DOUBLE [not null, default: "0"]
  "tp" DOUBLE [not null, default: "0"]
  "active" TINYINT(4) [not null, default: "1"]
  "ticket_id" INT(11) [default: NULL]
  "mt4server" INT(11) [not null, default: "0"]
  "commission" DOUBLE [default: NULL]
  "storage" DOUBLE [default: NULL]
  "profit" DOUBLE [default: NULL]
  "pips" INT(11) [default: NULL]
  "close_price" DOUBLE [default: NULL]
  "close_time" TIMESTAMP [default: NULL]
  "expired" INT(11) [default: NULL]
  "reason" TINYINT(4) [not null, default: "0"]
  "state" TINYINT(4) [not null, default: "0"]
  "notified" TINYINT(1) [not null, default: "0", note: '0: not sent yet, 1: email sent']
  "profit_scale" DOUBLE [default: NULL]
  "CREATED_AT" TIMESTAMP [default: NULL]
  "LAST_MODIFY" TIMESTAMP [default: NULL]

Indexes {
  channel_id [name: "channel_id"]
  symbol [name: "symbol"]
  op [name: "op"]
  open_time [name: "open_time"]
  active [name: "active"]
  profit [name: "profit"]
  pips [name: "pips"]
  expired [name: "expired"]
  notified [name: "notified"]
  close_time [name: "close_time"]
  profit_scale [name: "profit_scale"]
  CREATED_AT [name: "CREATED_AT"]
  LAST_MODIFY [name: "LAST_MODIFY"]
}
}
