Table "dw_date_dimension" {
  "utc_datetime_start" DATETIME [pk, not null]
  "utc_datetime_end" DATETIME [not null]
  "utc_unix_start" BIGINT(20) [default: NULL]
  "utc_unix_end" BIGINT(20) [default: NULL]
  "dd_gmt" TINYINT(4) [not null]
  "dd_date" DATE [default: NULL]
  "dd_year" SMALLINT(6) [default: NULL]
  "dd_month" SMALLINT(6) [default: NULL]
  "dd_day" SMALLINT(6) [default: NULL]
  "dd_yearweek" SMALLINT(6) [default: NULL]
  "dd_quarter" SMALLINT(6) [default: NULL]
  "dd_month_name" CHAR(10) [default: NULL]
  "dd_day_name" CHAR(10) [default: NULL]
  "dd_nama_bulan" CHAR(10) [default: NULL]
  "dd_nama_hari" CHAR(10) [default: NULL]

Indexes {
  utc_datetime_end [unique, name: "utc_datetime_end"]
  utc_unix_start [unique, name: "utc_unix_start"]
  utc_unix_end [unique, name: "utc_unix_end"]
  dd_date [name: "dd_date"]
  dd_gmt [name: "dd_gmt"]
  dd_year [name: "dd_year"]
  dd_month [name: "dd_month"]
  dd_day [name: "dd_day"]
  dd_yearweek [name: "dd_yearweek"]
  dd_quarter [name: "dd_quarter"]
  dd_month_name [name: "dd_month_name"]
  dd_day_name [name: "dd_day_name"]
  dd_nama_bulan [name: "dd_nama_bulan"]
  dd_nama_hari [name: "dd_nama_hari"]
  (utc_unix_start, utc_unix_end) [name: "utc_unix_start_utc_unix_end"]
}
}
