Table "tfcampus_registration" {
  "id" INT(11) [pk, not null, increment]
  "email" VARCHAR(50) [not null]
  "class" INT(11) [not null]
  "notelp" VARCHAR(50) [not null]
  "alamat" TEXT [not null]
  "experience" TINYINT(4) [not null, default: "0"]
  "longexp" VARCHAR(50) [default: NULL]
  "broker" VARCHAR(50) [default: NULL]
  "jenisacc" VARCHAR(50) [default: NULL]
  "leverage" VARCHAR(50) [default: NULL]
  "averagelot" VARCHAR(50) [default: NULL]
  "umur" INT(3) [not null]
  "pekerjaan" VARCHAR(50) [not null]
  "refname" VARCHAR(50) [default: NULL]
  "method" VARCHAR(50) [default: NULL]
  "source" VARCHAR(50) [default: NULL]
  "registered" INT(11) [not null]
  "reason" VARCHAR(50) [default: NULL]
  "status" TINYINT(4) [not null, default: "1", note: '0: disable; 1:enable']
  "params" TEXT [default: NULL]
}
