Table "traders_contact_request" {
  "id" INT(11) [pk, not null, increment]
  "waktu" DATETIME [not null]
  "userid" INT(11) [not null]
  "phone" VARCHAR(50) [not null]
  "email" VARCHAR(50) [not null]
  "notes_internal" TEXT [default: NULL]
  "notes" TEXT [default: NULL]
  "comments" TEXT [default: NULL]
  "status" INT(11) [not null, default: "0", note: '0 Not Processed, 1 Sukses, 2 Failed, 3 Waiting']
  "source" VARCHAR(50) [not null, note: 'Recommend, Callback']
  "created_at" DATETIME [default: NULL]
  "updated_at" DATETIME [default: NULL]

Indexes {
  userid [name: "USERID"]
  email [name: "EMAIL"]
  created_at [name: "created_at"]
  updated_at [name: "updated_at"]
}
}
