Table "users" {
  "id" INT(5) [pk, not null, increment]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(75) [not null]
  "fullname" VARCHAR(50) [not null]
  "phone" VARCHAR(50) [not null]
  "country" VARCHAR(50) [default: NULL]
  "tglaktif" INT(10) [not null]
  "first_visit" TEXT [default: NULL]
  "first_referrer" TEXT [default: NULL]
  "last_referrer" TEXT [default: NULL]
  "goal_referrer" TEXT [default: NULL]
  "last_visit" INT(10) [not null, default: "0"]
  "utm_campaign" VARCHAR(128) [default: NULL]
  "utm_source" VARCHAR(128) [default: NULL]
  "utm_medium" VARCHAR(128) [default: NULL]
  "utm_term" VARCHAR(128) [default: NULL]
  "utm_content" VARCHAR(128) [default: NULL]
  "campaignid" VARCHAR(128) [default: NULL]
  "adgroupid" VARCHAR(128) [default: NULL]
  "adid" VARCHAR(128) [default: NULL]
  "gclid" VARCHAR(255) [default: NULL]
  "pathdir" VARCHAR(6) [default: NULL]
  "facebook" BIGINT(15) [not null, default: "0"]
  "google" INT(1) [not null, default: "0", note: '1: register, 2: used login only']
  "yahoo" INT(1) [not null, default: "0"]
  "last_reset" INT(11) [default: NULL]
  "alumni" TINYINT(4) [not null, default: "0"]
  "deleted" TINYINT(4) [not null, default: "0"]
  "subscribe" TINYINT(4) [not null, default: "0"]
  "protection" TINYINT(4) [not null, default: "0"]
  "verify" TINYINT(4) [not null, default: "0"]
  "language" VARCHAR(50) [default: NULL]
  "fbtoken" VARCHAR(255) [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  fbtoken [unique, name: "fbtoken"]
  email [name: "email"]
  tglaktif [name: "tglaktif"]
  utm_campaign [name: "utm_campaign"]
  utm_source [name: "utm_source"]
  utm_medium [name: "utm_medium"]
  utm_term [name: "utm_term"]
  campaignid [name: "campaignid"]
  adgroupid [name: "adgroupid"]
  adid [name: "adid"]
  gclid [name: "gclid"]
  utm_content [name: "utm_content"]
}
}
