Table "user_analytics" {
  "userid" INT(11) [pk, not null]
  "ad_id" INT(11) [default: NULL]
  "adgroup_id" INT(11) [default: NULL]
  "campaign_id" INT(11) [default: NULL]
  "first_ad_id" INT(11) [default: NULL]
  "first_adgroup_id" INT(11) [default: NULL]
  "first_campaign_id" INT(11) [default: NULL]
  "first_visit" TEXT [default: NULL]
  "first_source" VARCHAR(50) [default: NULL]
  "first_medium" VARCHAR(50) [default: NULL]
  "first_ref" TEXT [default: NULL]
  "first_campaign" VARCHAR(50) [default: NULL]
  "first_content" VARCHAR(50) [default: NULL]
  "last_ad_id" INT(11) [default: NULL]
  "last_adgroup_id" INT(11) [default: NULL]
  "last_campaign_id" INT(11) [default: NULL]
  "last_visit" TEXT [default: NULL]
  "last_source" VARCHAR(50) [default: NULL]
  "last_medium" VARCHAR(50) [default: NULL]
  "last_ref" TEXT [default: NULL]
  "last_campaign" VARCHAR(50) [default: NULL]
  "last_content" VARCHAR(50) [default: NULL]
  "client_id" VARCHAR(128) [default: NULL]
}