CREATE TABLE `data_wilayah` (
	`KODE_WILAYAH` VARCHAR(8) NOT NULL,
	`MST_KODE_WILAYAH` VARCHAR(8) NOT NULL,
	`NAMA` VARCHAR(255) NOT NULL,
	`LEVEL` ENUM('1','2','3','4') NOT NULL,
	PRIMARY KEY (`KODE_WILAYAH`),
	UNIQUE INDEX `UNIQUE` (`MST_KODE_WILAYAH`, `KODE_WILAYAH`)
);
