CREATE TABLE `dsc_payment` (
	`bill_no` INT(11) NOT NULL AUTO_INCREMENT,
	`bill_reff` INT(11) NOT NULL COMMENT 'Channel ID',
	`bill_code` SMALLINT(6) NOT NULL DEFAULT '0',
	`bill_date` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
	`bill_expired` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
	`bill_desc` VARCHAR(128) NOT NULL DEFAULT '',
	`bill_currency` CHAR(3) NOT NULL DEFAULT '',
	`bill_total` DOUBLE(22,0) NOT NULL DEFAULT '0',
	`payment_channel` INT(11) NOT NULL,
	`pay_type` TINYINT(4) NOT NULL DEFAULT '0',
	`cust_no` INT(11) NOT NULL,
	`cust_name` VARCHAR(128) NOT NULL DEFAULT '',
	`msisdn` VARCHAR(64) NOT NULL DEFAULT '',
	`email` VARCHAR(128) NOT NULL DEFAULT '',
	`terminal` CHAR(2) NOT NULL DEFAULT '',
	`product` VARCHAR(50) NOT NULL DEFAULT '',
	`amount` DOUBLE(22,0) NOT NULL DEFAULT '0',
	`qty` INT(11) NOT NULL DEFAULT '0',
	`payment_plan` TINYINT(4) NOT NULL DEFAULT '0',
	`tenor` CHAR(2) NOT NULL DEFAULT '',
	`trx_id` VARCHAR(16) NULL DEFAULT NULL,
	`payment_total` DOUBLE NOT NULL DEFAULT '0',
	`payment_date` DATETIME NULL DEFAULT NULL,
	`payment_status` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0 Belum diproses; 1 Dalam proses; 2 Payment Success; 4 Payment Reserval; 5 Tagihan tidak ditemukan; 7 Payment Refused; 8 Payment Cancelled; 9 Unknown',
	`payment_reff` VARCHAR(32) NULL DEFAULT NULL,
	`comm` DOUBLE NULL DEFAULT NULL,
	`admin_fee` DOUBLE NULL DEFAULT NULL,
	`subs_expired` DATETIME NULL DEFAULT NULL,
	`source` TINYINT(4) NULL DEFAULT '1' COMMENT '0: Internal, 1: Faspay',
	PRIMARY KEY (`bill_no`),
	INDEX `cust_no` (`cust_no`),
	INDEX `payment_channel` (`payment_channel`),
	INDEX `bill_reff` (`bill_reff`),
	INDEX `payment_date` (`payment_date`),
	INDEX `bill_code` (`bill_code`)
)
COMMENT='https://faspay.co.id/docs/'
AUTO_INCREMENT=197
;
