CREATE TABLE `dsc_signals` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`channel_id` INT(11) NOT NULL DEFAULT '0',
	`volume` INT(11) NOT NULL DEFAULT '0',
	`symbol` VARCHAR(30) NULL DEFAULT NULL,
	`op` TINYINT(4) NULL DEFAULT NULL,
	`open_time` DATETIME NULL DEFAULT NULL,
	`price` DOUBLE NOT NULL DEFAULT '0',
	`sl` DOUBLE NOT NULL DEFAULT '0',
	`tp` DOUBLE NOT NULL DEFAULT '0',
	`active` TINYINT(4) NOT NULL DEFAULT '1',
	`ticket_id` INT(11) NULL DEFAULT NULL,
	`mt4server` INT(11) NOT NULL DEFAULT '0',
	`commission` DOUBLE NULL DEFAULT NULL,
	`storage` DOUBLE NULL DEFAULT NULL,
	`profit` DOUBLE NULL DEFAULT NULL,
	`pips` INT(11) NULL DEFAULT NULL,
	`close_price` DOUBLE NULL DEFAULT NULL,
	`close_time` TIMESTAMP NULL DEFAULT NULL,
	`expired` INT(11) NULL DEFAULT NULL,
	`reason` TINYINT(4) NOT NULL DEFAULT '0',
	`state` TINYINT(4) NOT NULL DEFAULT '0',
	`notified` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0: not sent yet, 1: email sent',
	`profit_scale` DOUBLE NULL DEFAULT NULL,
	`CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
	`LAST_MODIFY` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	INDEX `channel_id` (`channel_id`),
	INDEX `symbol` (`symbol`),
	INDEX `op` (`op`),
	INDEX `open_time` (`open_time`),
	INDEX `active` (`active`),
	INDEX `profit` (`profit`),
	INDEX `pips` (`pips`),
	INDEX `expired` (`expired`),
	INDEX `notified` (`notified`),
	INDEX `close_time` (`close_time`),
	INDEX `profit_scale` (`profit_scale`),
	INDEX `CREATED_AT` (`CREATED_AT`),
	INDEX `LAST_MODIFY` (`LAST_MODIFY`)
)
AUTO_INCREMENT=1532685
;