CREATE TABLE `dsc_subs_auto_copy` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`channelid` INT(11) NULL DEFAULT NULL,
	`user_id` INT(11) NULL DEFAULT NULL,
	`mt4server` INT(11) NULL DEFAULT NULL,
	`account` INT(11) NULL DEFAULT NULL,
	`volume` INT(11) NULL DEFAULT NULL,
	`symbol` VARCHAR(16) NULL DEFAULT NULL,
	`symbol_map` VARCHAR(16) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
AUTO_INCREMENT=539
;
