CREATE TABLE `dsc_assistants` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` TEXT NULL DEFAULT NULL,
	`param` TEXT NULL DEFAULT NULL,
	`price` DOUBLE NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
AUTO_INCREMENT=2
;
