CREATE TABLE `dsc_commission` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`nominal` DOUBLE NOT NULL,
	`userid` INT(10) UNSIGNED NOT NULL,
	`CREATED_AT` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
