CREATE TABLE `dsc_channels_point_events` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`channel_id` INT(11) NOT NULL DEFAULT '0',
	`utc_start` DATETIME NULL DEFAULT NULL,
	`utc_end` DATETIME NULL DEFAULT NULL,
	`settle_signals` INT(11) NOT NULL DEFAULT '0',
	`total_signals_created` INT(11) NOT NULL DEFAULT '0',
	`total_signals_closed` INT(11) NOT NULL DEFAULT '0',
	`total_pips` INT(11) NOT NULL DEFAULT '0',
	`avg_pips` DOUBLE NOT NULL DEFAULT '0',
	`point` DOUBLE NOT NULL DEFAULT '0',
	`medals` TINYINT(4) NOT NULL DEFAULT '0',
	`last_qualify_id` INT(11) NOT NULL DEFAULT '0',
	`prev_point` DOUBLE NOT NULL DEFAULT '0',
	`prev_medal` TINYINT(4) NOT NULL DEFAULT '0',
	`prev_channel_medal` TINYINT(4) NOT NULL DEFAULT '0',
	`last_avg_pips_monthly` DOUBLE NULL DEFAULT NULL,
	`next_avg_profit_monthly` DOUBLE NULL DEFAULT NULL,
	`send_mail` TINYINT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `channel_id_utc_start_utc_end` (`channel_id`, `utc_start`, `utc_end`),
	INDEX `channel_id` (`channel_id`),
	INDEX `dt_start` (`utc_start`),
	INDEX `dt_end` (`utc_end`),
	INDEX `point` (`point`),
	INDEX `medals` (`medals`),
	INDEX `prev_month_point` (`prev_point`),
	INDEX `prev_month_medal` (`prev_medal`),
	INDEX `settle_signals` (`settle_signals`),
	INDEX `total_pips` (`total_pips`),
	INDEX `avg_pips` (`avg_pips`),
	INDEX `prev_channel_medal` (`prev_channel_medal`),
	INDEX `total_signals_created` (`total_signals_created`),
	INDEX `total_signals_closed` (`total_signals_closed`),
	INDEX `last_qualify_id` (`last_qualify_id`),
	INDEX `last_avg_pips_monthly` (`last_avg_pips_monthly`),
	INDEX `next_avg_profit_monthly` (`next_avg_profit_monthly`)
)
AUTO_INCREMENT=1248
;