CREATE TABLE `dw_date_dimension` (
	`utc_datetime_start` DATETIME NOT NULL,
	`utc_datetime_end` DATETIME NOT NULL,
	`utc_unix_start` BIGINT(20) NULL DEFAULT NULL,
	`utc_unix_end` BIGINT(20) NULL DEFAULT NULL,
	`dd_gmt` TINYINT(4) NOT NULL,
	`dd_date` DATE NULL DEFAULT NULL,
	`dd_year` SMALLINT(6) NULL DEFAULT NULL,
	`dd_month` SMALLINT(6) NULL DEFAULT NULL,
	`dd_day` SMALLINT(6) NULL DEFAULT NULL,
	`dd_yearweek` SMALLINT(6) NULL DEFAULT NULL,
	`dd_quarter` SMALLINT(6) NULL DEFAULT NULL,
	`dd_month_name` CHAR(10) NULL DEFAULT NULL,
	`dd_day_name` CHAR(10) NULL DEFAULT NULL,
	`dd_nama_bulan` CHAR(10) NULL DEFAULT NULL,
	`dd_nama_hari` CHAR(10) NULL DEFAULT NULL,
	PRIMARY KEY (`utc_datetime_start`),
	UNIQUE INDEX `utc_datetime_end` (`utc_datetime_end`),
	UNIQUE INDEX `utc_unix_start` (`utc_unix_start`),
	UNIQUE INDEX `utc_unix_end` (`utc_unix_end`),
	INDEX `dd_date` (`dd_date`),
	INDEX `dd_gmt` (`dd_gmt`),
	INDEX `dd_year` (`dd_year`),
	INDEX `dd_month` (`dd_month`),
	INDEX `dd_day` (`dd_day`),
	INDEX `dd_yearweek` (`dd_yearweek`),
	INDEX `dd_quarter` (`dd_quarter`),
	INDEX `dd_month_name` (`dd_month_name`),
	INDEX `dd_day_name` (`dd_day_name`),
	INDEX `dd_nama_bulan` (`dd_nama_bulan`),
	INDEX `dd_nama_hari` (`dd_nama_hari`),
	INDEX `utc_unix_start_utc_unix_end` (`utc_unix_start`, `utc_unix_end`)
);
