CREATE TABLE `mtf_signals` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NOT NULL,
	`symbol` VARCHAR(30) NOT NULL,
	`op` TINYINT(4) NOT NULL,
	`price` VARCHAR(50) NOT NULL,
	`sl` VARCHAR(50) NOT NULL,
	`tp` VARCHAR(50) NOT NULL,
	`active` TINYINT(4) NOT NULL DEFAULT '1',
	`CREATED_AT` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`MODIFY_TIME` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
AUTO_INCREMENT=3
;