CREATE TABLE `tf_protection` (
	`no` INT(11) NULL DEFAULT NULL,
	`fullname` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`phone` VARCHAR(50) NULL DEFAULT NULL,
	`plat_id` VARCHAR(50) NULL DEFAULT NULL,
	`reff` VARCHAR(50) NULL DEFAULT NULL,
	`source` VARCHAR(50) NULL DEFAULT NULL
)
COMMENT='utk pencocokan data docs'
;