CREATE TABLE `tfcampus_class` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`from` DATE NOT NULL,
	`end` DATE NOT NULL,
	`capacity` SMALLINT(6) NOT NULL,
	`price` INT(11) NOT NULL,
	`cmeet` TINYINT(3) NOT NULL DEFAULT '0',
	`cabang` VARCHAR(3) NULL DEFAULT NULL,
	`city` VARCHAR(50) NULL DEFAULT NULL,
	`location` TEXT NOT NULL,
	`map` VARCHAR(50) NOT NULL,
	`deleted` TINYINT(4) NOT NULL DEFAULT '0',
	`extra` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
AUTO_INCREMENT=44
;
