CREATE TABLE `tp_product` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`jenis` VARCHAR(5) NOT NULL,
	`nominal` INT(11) NOT NULL,
	`from` DATETIME NOT NULL,
	`to` DATETIME NOT NULL,
	`expired` SMALLINT(5) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
)
AUTO_INCREMENT=13
;