CREATE TABLE `user_analytics` (
	`userid` INT(11) NOT NULL,
	`ad_id` INT(11) NULL DEFAULT NULL,
	`adgroup_id` INT(11) NULL DEFAULT NULL,
	`campaign_id` INT(11) NULL DEFAULT NULL,
	`first_ad_id` INT(11) NULL DEFAULT NULL,
	`first_adgroup_id` INT(11) NULL DEFAULT NULL,
	`first_campaign_id` INT(11) NULL DEFAULT NULL,
	`first_visit` TEXT NULL DEFAULT NULL,
	`first_source` VARCHAR(50) NULL DEFAULT NULL,
	`first_medium` VARCHAR(50) NULL DEFAULT NULL,
	`first_ref` TEXT NULL DEFAULT NULL,
	`first_campaign` VARCHAR(50) NULL DEFAULT NULL,
	`first_content` VARCHAR(50) NULL DEFAULT NULL,
	`last_ad_id` INT(11) NULL DEFAULT NULL,
	`last_adgroup_id` INT(11) NULL DEFAULT NULL,
	`last_campaign_id` INT(11) NULL DEFAULT NULL,
	`last_visit` TEXT NULL DEFAULT NULL,
	`last_source` VARCHAR(50) NULL DEFAULT NULL,
	`last_medium` VARCHAR(50) NULL DEFAULT NULL,
	`last_ref` TEXT NULL DEFAULT NULL,
	`last_campaign` VARCHAR(50) NULL DEFAULT NULL,
	`last_content` VARCHAR(50) NULL DEFAULT NULL,
	`client_id` VARCHAR(128) NULL DEFAULT NULL,
	PRIMARY KEY (`userid`)
);